data_config:
  time_frame: "M15"
  start_date: "2024-07-21"
  end_date: "2025-07-20"

signal_settings:
  asian_time_range_start: "00:00"
  asian_time_range_end: "05:00"
  london_start: 8
  london_end: 10
  TP_mode: "Asian_range"
  SL_mode: "Asian_range"

rates:
  "EURUSD": 1.0,     # Already in USD
  "GBPUSD": 1.0,    # Already in USD
  "GBPJPY": 0.007,   # 1 JPY = 0.007 USD